      Subroutine Type835

! Object: PV model (for PVT collectors)
! Simulation Studio Model: Type835
! 

! Author: Danny Jonas
! Editor: Danny Jonas
! Date:	 August 18, 2017
! last modified: January 19, 2018
! 
! Modifications: 
!           19.01.2018, DJ: Change Tref ind Tcell_ref and gross area as information added
!
! *** 
! *** Model Parameters 
! *** 
!			Area - Area of the  PVT collectors or PV modules (gross area)	m^2 [0;+Inf]
!			Eta_ref - electrical efficiency at reference conditions	(gross area) - [0;1]
!			PVTmode - mode for PV cell temperature calculation	- [1;2]
!			b0 - constant for IAM	- [0;1]
!			beta - temperature coefficient of solar cell efficiency	any [0;1]
!			Tcell_ref - Cell temperature at reference conditions 	C [-Inf;+Inf]
!			Uabsfl - internal heat transfer coefficient connecting cell and fluid temperature	W/m^2.K [0;+Inf]
!			PVmode - mode for the irradiance dependence calculation of the PV efficiency	- [1;2]
!			a - model parameter a for PV efficiency	m2/W [-Inf;+Inf]
!			b - model parameter a for PV efficiency	- [-Inf;+Inf]
!			c - model parameter a for PV efficiency	- [-Inf;+Inf]
!			U0 - coeff. for module temperature (radiation)	W/m^2.K [-Inf;+Inf]
!			U1 - coeff. for module temperature (wind) W.s/m^3.K [-Inf;+Inf]

! *** 
! *** Model Inputs 
! *** 
!			It - Global radiation on PV plane	kJ/hr.m^2 [0;+Inf]
!			Theta - Incidence angle of beam radiation	degrees [-360;+360]
!			Tm - mean fluid temperature of the PVT collector	C [-Inf;+Inf]
!			qth - specific thermal power output of the PVT collector	kJ/hr.m^2 [-Inf;+Inf]
!			u - wind speed in the PV plane	m/s [0;+Inf]
!			Tamb - ambient air temperature	C [-Inf;+Inf]

! *** 
! *** Model Outputs 
! *** 
!			Pel - Electric power output	kJ/hr [-Inf;+Inf]
!			Tcell - temperature of the PV cell	C [-Inf;+Inf]
!			Eta PV - total efficiency of PV modules (gross area) % (base 1) [0;1]

! *** 
! *** Model Derivatives 
! *** 

! (Comments and routine interface generated by TRNSYS Simulation Studio)
!************************************************************************

!-----------------------------------------------------------------------------------------------------------------------
! This TRNSYS component skeleton was generated from the TRNSYS studio based on the user-supplied parameters, inputs, 
! outputs, and derivatives.  The user should check the component formulation carefully and add the content to transform
! the parameters, inputs and derivatives into outputs.  Remember, outputs should be the average value over the timestep
! and not the value at the end of the timestep; although in many models these are exactly the same values.  Refer to 
! existing types for examples of using advanced features inside the model (Formats, Labels etc.)
!-----------------------------------------------------------------------------------------------------------------------


      Use TrnsysConstants
      Use TrnsysFunctions

!-----------------------------------------------------------------------------------------------------------------------

!DEC$Attributes DLLexport :: Type835

!-----------------------------------------------------------------------------------------------------------------------
!Trnsys Declarations
      Implicit None

      Double Precision Timestep,Time
      Integer CurrentUnit,CurrentType


!    PARAMETERS
      DOUBLE PRECISION Area
      DOUBLE PRECISION Eta_ref
      INTEGER PVTmode
      DOUBLE PRECISION b0
      DOUBLE PRECISION beta
      DOUBLE PRECISION Tcell_ref
      DOUBLE PRECISION Uabsfl
      INTEGER PVmode
      DOUBLE PRECISION a
      DOUBLE PRECISION b
      DOUBLE PRECISION c
      DOUBLE PRECISION U0
      DOUBLE PRECISION U1     
      
!    INPUTS
      DOUBLE PRECISION It
      DOUBLE PRECISION Theta
      DOUBLE PRECISION Tm
      DOUBLE PRECISION qth
      DOUBLE PRECISION u
      DOUBLE PRECISION Tamb

!    OUTPUTS
      DOUBLE PRECISION Pel
      DOUBLE PRECISION Tcell
      DOUBLE PRECISION EtaPV
      
!    LOCAL
      DOUBLE PRECISION PRiam
      DOUBLE PRECISION PRt
      DOUBLE PRECISION PRg
      DOUBLE PRECISION PRtot
      DOUBLE PRECISION Pelspec
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Get the Global Trnsys Simulation Variables
      Time=getSimulationTime()
      Timestep=getSimulationTimeStep()
      CurrentUnit = getCurrentUnit()
      CurrentType = getCurrentType()
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Version Number for This Type
      If(getIsVersionSigningTime()) Then
		Call SetTypeVersion(17)
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do Any Last Call Manipulations Here
      If(getIsLastCallofSimulation()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Perform Any "After Convergence" Manipulations That May Be Required at the End of Each Timestep
      If(getIsEndOfTimestep()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the "Very First Call of the Simulation Manipulations" Here
      If(getIsFirstCallofSimulation()) Then

		!Tell the TRNSYS Engine How This Type Works
		Call SetNumberofParameters(13)           !The number of parameters that the the model wants
		Call SetNumberofInputs(6)                   !The number of inputs that the the model wants
		Call SetNumberofDerivatives(0)         !The number of derivatives that the the model wants
		Call SetNumberofOutputs(3)                 !The number of outputs that the the model produces
		Call SetIterationMode(1)                             !An indicator for the iteration mode (default=1).  Refer to section 8.4.3.5 of the documentation for more details.
		Call SetNumberStoredVariables(0,0)                   !The number of static variables that the model wants stored in the global storage array and the number of dynamic variables that the model wants stored in the global storage array
		Call SetNumberofDiscreteControls(0)               !The number of discrete control functions set by this model (a value greater than zero requires the user to use Solver 1: Powell's method)

        !Set the Correct Input and Output Variable Types
        Call SetInputUnits(1,'IR1')
        Call SetInputUnits(2,'DG1')
        Call SetInputUnits(3,'TE1')
        Call SetInputUnits(4,'IR1')
        Call SetInputUnits(5,'VE1')
        Call SetInputUnits(6,'TE1')
          
        Call SetOutputUnits(1,'PW1')
        Call SetOutputUnits(2,'TE1')
        Call SetOutputUnits(3,'DM1')        
          
		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the First Timestep Manipulations Here - There Are No Iterations at the Intial Time
      If (getIsStartTime()) Then
      Area = getParameterValue(1)
      Eta_ref = getParameterValue(2)
      PVTmode = getParameterValue(3)
      b0 = getParameterValue(4)
      beta = getParameterValue(5)
      Tcell_ref = getParameterValue(6)
      Uabsfl = getParameterValue(7)*3.6d0
      PVmode = getParameterValue(8)
      a = getParameterValue(9)
      b = getParameterValue(10)
      c = getParameterValue(11)
      U0 = getParameterValue(12)*3.6d0
      U1 = getParameterValue(13)*3.6d0


      It = GetInputValue(1)
      Theta = GetInputValue(2)
      Tm = GetInputValue(3)
      qth = GetInputValue(4)
      u = GetInputValue(5)
      Tamb = GetInputValue(6)

	
   !Check the Parameters for Problems (#,ErrorType,Text)
   !Sample Code: If( PAR1 <= 0.) Call FoundBadParameter(1,'Fatal','The first parameter provided to this model is not acceptable.')

   !Set the Initial Values of the Outputs (#,Value)
		Call SetOutputValue(1, 0) ! Pel - Electric power output
		Call SetOutputValue(2, 0) ! Tcell - temperature of the PV cell
		Call SetOutputValue(3, 0) ! EtaPV - total efficiency of PV modules


   !If Needed, Set the Initial Values of the Static Storage Variables (#,Value)
   !Sample Code: SetStaticArrayValue(1,0.d0)

   !If Needed, Set the Initial Values of the Dynamic Storage Variables (#,Value)
   !Sample Code: Call SetDynamicArrayValueThisIteration(1,20.d0)

   !If Needed, Set the Initial Values of the Discrete Controllers (#,Value)
   !Sample Code for Controller 1 Set to Off: Call SetDesiredDiscreteControlState(1,0) 

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!ReRead the Parameters if Another Unit of This Type Has Been Called Last
      If(getIsReReadParameters()) Then
		!Read in the Values of the Parameters from the Input File
      Area = getParameterValue(1)
      Eta_ref = getParameterValue(2)
      PVTmode = getParameterValue(3)
      b0 = getParameterValue(4)
      beta = getParameterValue(5)
      Tcell_ref = getParameterValue(6)
      Uabsfl = getParameterValue(7)*3.6d0
      PVmode = getParameterValue(8)
      a = getParameterValue(9)
      b = getParameterValue(10)
      c = getParameterValue(11)
      U0 = getParameterValue(12)*3.6d0
      U1 = getParameterValue(13)*3.6d0
		
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!Read the Inputs
      It = GetInputValue(1)
      Theta = GetInputValue(2)
      Tm = GetInputValue(3)
      qth = GetInputValue(4)
      u = GetInputValue(5)
      Tamb = GetInputValue(6)
		

	!Check the Inputs for Problems (#,ErrorType,Text)
	!Sample Code: If( IN1 <= 0.) Call FoundBadInput(1,'Fatal','The first input provided to this model is not acceptable.')
 
      If(ErrorFound()) Return
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!    *** PERFORM ALL THE CALCULATION HERE FOR THIS MODEL. ***
!-----------------------------------------------------------------------------------------------------------------------
                  
	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Previous Control States if Discrete Controllers are Being Used (#)
	!Sample Code: CONTROL_LAST=getPreviousControlState(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Values from the Global Storage Array for the Static Variables (#)
	!Sample Code: STATIC1=getStaticArrayValue(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Initial Values of the Dynamic Variables from the Global Storage Array (#)
	!Sample Code: T_INITIAL_1=getDynamicArrayValueLastTimestep(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
 	!Perform All of the Calculations Here to Set the Outputs from the Model Based on the Inputs

	!Sample Code: OUT1=IN1+PAR1   

	!If the model requires the solution of numerical derivatives, set these derivatives and get the current solution
	!Sample Code: T1=getNumericalSolution(1)
	!Sample Code: T2=getNumericalSolution(2)
	!Sample Code: DTDT1=3.*T2+7.*T1-15.
	!Sample Code: DTDT2=-2.*T1+11.*T2+21.
	!Sample Code: Call SetNumericalDerivative(1,DTDT1)
	!Sample Code: Call SetNumericalDerivative(2,DTDT2) 
      
!------------------------------------------------------------------------------
!    Calculation of PR IAM
!------------------------------------------------------------------------------
      
    PRiam = 1.d0-b0*(1/cos(Theta)-1) 
      
!---------------------------------------------------------------------------------------


!------------------------------------------------------------------------------
!    Calculation of Tcell
!------------------------------------------------------------------------------

    If(PVTmode==1) Then
    
    Tcell = qth/(Uabsfl)+Tm 
    
    Else
    
    Tcell = Tamb + It/(U0+U1*u)
    
    Endif
!---------------------------------------------------------------------------------------


!------------------------------------------------------------------------------
!    Calculation of PR T
!------------------------------------------------------------------------------
      
    PRt = 1.d0 - beta/100 * (Tcell-Tcell_ref) 
      
!---------------------------------------------------------------------------------------


!------------------------------------------------------------------------------
!    Calculation of PR G
!------------------------------------------------------------------------------
      
    PRg = a*It/3.6d0+b*LOG(It/3.6d0+1.d0)+c*((LOG(It/3.6d0+EXP(1.d0)))**2.d0/(It/3.6d0+1.d0)-1.d0) 
      
!---------------------------------------------------------------------------------------

!------------------------------------------------------------------------------
!    Calculation of PRtot, Pelspec, Pel and EtaPV
!------------------------------------------------------------------------------
      
    PRtot = PRiam*PRt*PRg
    Pelspec = Eta_ref*PRtot*It
    Pel = Pelspec*Area
    EtaPV = Eta_ref*PRtot
    
!---------------------------------------------------------------------------------------



!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Outputs from this Model (#,Value)
		Call SetOutputValue(1, Pel) ! Pel - Electric power output
		Call SetOutputValue(2, Tcell) ! Tcell - temperature of the PV cell
		Call SetOutputValue(3, EtaPV) ! EtaPV - total efficiency of PV modules

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Desired Disceret Control Signal Values for this Iteration (#,State)
!Sample Code:  Call SetDesiredDiscreteControlState(1,1)
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Final value of the Dynamic Variables in the Global Storage Array (#,Value)
!Sample Code:  Call SetDynamicArrayValueThisIteration(1,T_FINAL_1)
!-----------------------------------------------------------------------------------------------------------------------
 
      Return
      End
!-----------------------------------------------------------------------------------------------------------------------

