      Subroutine Type835

! Object: PV model (for PVT collectors)
! Simulation Studio Model: Type835
! 

! Author: Danny Jonas
! Editor: Danny Jonas
! Date:	 August 18, 2017
! Version: 3.3   
! last modified: October 11, 2018
! 
! Modifications: 
!           19.01.2018, DJ: Change Tref ind Tcell_ref and gross area as information added
!           23.01.2018, DJ: Change and add model parameters, inputs and outputs to version 2.0   
!           23.01.2018, DJ: Change code to version 3.0            
!           22.02.2018, DJ: Bugfixes: Additional Calculation for theta in radians, maximum for theta and PRiam for negative values equal to zero 
!           02.10.2018, DJ: Bugfixes: It for negative values equal to zero; Nomenclature Ucellfl
!           11.10.2018, DJ: - Add Error Types / Parameter Checking
!                           - Set all numbers as DoublePrecision values .d0 (including output values)
!                           - Delete Input values at StartTime Manipulations
!                           - Change PRiam calculation with PRiam zero if there is no incident solar, or if the incidence angle is 
!                           lower / greater than the possible acceptance angle (0° - 90°)
! *** 
! *** Model Parameters 
! *** 
!			PVTmode - mode for PV cell temperature calculation	- [1;2]
!			PVmode - mode for the irradiance dependence calculation of the PV efficiency	- [1;1]
!			PVcellmode - mode for PV cell temperature calculation of stand-alone PV	- [1;3]
!			Area - Area of the  PVT collectors or PV modules 	m^2 [0;+Inf]
!			Eta_ref - electrical efficiency at reference conditions 	- [0;1]
!			b0 - constant for IAM	- [0;1]
!			beta - temperature coefficient of solar cell efficiency	- [0;1]
!			Tcell_ref - PV Cell temperature at reference conditions 	C [-Inf;+Inf]
!			a - model parameter a for PV efficiency	m2/W [-Inf;+Inf]
!			b - model parameter a for PV efficiency	- [-Inf;+Inf]
!			c - model parameter a for PV efficiency	- [-Inf;+Inf]
!			Ucellfl - internal heat transfer coefficient connecting cell and fluid temperature	W/m^2.K [0;+Inf]
!			U0 - coeff. for module temperature (radiation)	W/m^2.K [-Inf;+Inf]
!			U1 - coeff. for module temperature (wind)	W.s/m^3.K [-Inf;+Inf]
!			Tcell_NOCT - PV Cell temperature at NOCT conditions	C [-Inf;+Inf]
!			Tamb_NOCT - ambient temperature at NOCT conditions	C [-Inf;+Inf]
!			It_NOCT - Global radiation on PV plane at NOCT conditions	W/m^2 [0;+Inf]
!			Taualpha - effective transmittance-absorptance product 	- [0;1]

! *** 
! *** Model Inputs 
! *** 
!			It - Global radiation on PV plane	kJ/hr.m^2 [0;+Inf]
!			Theta - Incidence angle of beam radiation	degrees [-360;+360]
!			Tm - mean fluid temperature of the PVT collector	C [-Inf;+Inf]
!			qth - specific thermal power output of the PVT collector	kJ/hr.m^2 [-Inf;+Inf]
!			u - wind speed in the PV plane	m/s [0;+Inf]
!			Tamb - ambient air temperature	C [-Inf;+Inf]
!			Tcell_in - temperature of the PV cell	C [-Inf;+Inf]

! *** 
! *** Model Outputs 
! *** 
!			Pel - Electric power output	kJ/hr [-Inf;+Inf]
!			Tcell - temperature of the PV cell	C [-Inf;+Inf]
!			EtaPV - total efficiency of PV modules (gross area)	- [0;1]

! *** 
! *** Model Derivatives 
! *** 

! (Comments and routine interface generated by TRNSYS Simulation Studio)
!************************************************************************

!-----------------------------------------------------------------------------------------------------------------------
! This TRNSYS component skeleton was generated from the TRNSYS studio based on the user-supplied parameters, inputs, 
! outputs, and derivatives.  The user should check the component formulation carefully and add the content to transform
! the parameters, inputs and derivatives into outputs.  Remember, outputs should be the average value over the timestep
! and not the value at the end of the timestep; although in many models these are exactly the same values.  Refer to 
! existing types for examples of using advanced features inside the model (Formats, Labels etc.)
!-----------------------------------------------------------------------------------------------------------------------


      Use TrnsysConstants
      Use TrnsysFunctions

!-----------------------------------------------------------------------------------------------------------------------

!DEC$Attributes DLLexport :: Type835

!-----------------------------------------------------------------------------------------------------------------------
!Trnsys Declarations
      Implicit None

      Double Precision Timestep,Time
      Integer CurrentUnit,CurrentType


!    PARAMETERS
      INTEGER PVTmode
      INTEGER PVmode
      INTEGER PVcellmode
      DOUBLE PRECISION Area
      DOUBLE PRECISION Eta_ref
      DOUBLE PRECISION b0
      DOUBLE PRECISION beta
      DOUBLE PRECISION Tcell_ref
      DOUBLE PRECISION a
      DOUBLE PRECISION b
      DOUBLE PRECISION c
      DOUBLE PRECISION Ucellfl
      DOUBLE PRECISION U0
      DOUBLE PRECISION U1 
      DOUBLE PRECISION Tcell_NOCT
      DOUBLE PRECISION Tamb_NOCT
      DOUBLE PRECISION It_NOCT
      DOUBLE PRECISION Taualpha
      
!    INPUTS
      DOUBLE PRECISION It
      DOUBLE PRECISION Theta
      DOUBLE PRECISION Tm
      DOUBLE PRECISION qth
      DOUBLE PRECISION u
      DOUBLE PRECISION Tamb
      DOUBLE PRECISION Tcell_in

!    OUTPUTS
      DOUBLE PRECISION Pel
      DOUBLE PRECISION Tcell
      DOUBLE PRECISION EtaPV
      
!    LOCAL
      DOUBLE PRECISION PRiam
      DOUBLE PRECISION PRt
      DOUBLE PRECISION PRg
      DOUBLE PRECISION PRtot
      DOUBLE PRECISION Pelspec
      DOUBLE PRECISION k1
      DOUBLE PRECISION k2
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Get the Global Trnsys Simulation Variables
      Time=getSimulationTime()
      Timestep=getSimulationTimeStep()
      CurrentUnit = getCurrentUnit()
      CurrentType = getCurrentType()
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Version Number for This Type
      If(getIsVersionSigningTime()) Then
		Call SetTypeVersion(17)
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do Any Last Call Manipulations Here
      If(getIsLastCallofSimulation()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Perform Any "After Convergence" Manipulations That May Be Required at the End of Each Timestep
      If(getIsEndOfTimestep()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the "Very First Call of the Simulation Manipulations" Here
      If(getIsFirstCallofSimulation()) Then

		!Tell the TRNSYS Engine How This Type Works
		Call SetNumberofParameters(18)           !The number of parameters that the the model wants
		Call SetNumberofInputs(7)                   !The number of inputs that the the model wants
		Call SetNumberofDerivatives(0)         !The number of derivatives that the the model wants
		Call SetNumberofOutputs(3)                 !The number of outputs that the the model produces
		Call SetIterationMode(1)                             !An indicator for the iteration mode (default=1).  Refer to section 8.4.3.5 of the documentation for more details.
		Call SetNumberStoredVariables(0,0)                   !The number of static variables that the model wants stored in the global storage array and the number of dynamic variables that the model wants stored in the global storage array
		Call SetNumberofDiscreteControls(0)               !The number of discrete control functions set by this model (a value greater than zero requires the user to use Solver 1: Powell's method)

        !Set the Correct Input and Output Variable Types
        Call SetInputUnits(1,'IR1')
        Call SetInputUnits(2,'DG1')
        Call SetInputUnits(3,'TE1')
        Call SetInputUnits(4,'IR1')
        Call SetInputUnits(5,'VE1')
        Call SetInputUnits(6,'TE1')
        Call SetInputUnits(7,'TE1')
          
        Call SetOutputUnits(1,'PW1')
        Call SetOutputUnits(2,'TE1')
        Call SetOutputUnits(3,'DM1')        
          
		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the First Timestep Manipulations Here - There Are No Iterations at the Intial Time
      If (getIsStartTime()) Then
      PVTmode = getParameterValue(1)
      PVmode = getParameterValue(2)
      PVcellmode = getParameterValue(3)
      Area = getParameterValue(4)
      Eta_ref = getParameterValue(5)
      b0 = getParameterValue(6)
      beta = getParameterValue(7)
      Tcell_ref = getParameterValue(8)
      a = getParameterValue(9)
      b = getParameterValue(10)
      c = getParameterValue(11)
      Ucellfl = getParameterValue(12)*3.6d0
      U0 = getParameterValue(13)*3.6d0
      U1 = getParameterValue(14)*3.6d0
      Tcell_NOCT = getParameterValue(15)
      Tamb_NOCT = getParameterValue(16)
      It_NOCT = getParameterValue(17)*3.6d0
      Taualpha = getParameterValue(18)
	
   !Check the Parameters for Problems (#,ErrorType,Text)
      If (Area < 0.d0) Call foundBadParameter(4,'Fatal','The area cannot be negative.')
      If ((Eta_ref < 0.d0) .or. (Eta_ref > 1.d0)) Call foundBadParameter(5,'Fatal','The electrical efficiency at reference conditions must be between 0 and 1.')
      If ((b0 < 0.d0) .or. (b0 > 1.d0)) Call foundBadParameter(6,'Fatal','The constant for IAM (b0) must be between 0 and 1.')
      If ((beta < 0.d0) .or. (beta > 1.d0)) Call foundBadParameter(7,'Fatal','The temperature coefficient of the solar cell efficiency must be between 0 and 1.')
      If (Ucellfl < 0.d0) Call foundBadParameter(12,'Fatal','The internal heat transfer coefficient connecting cell and fluid temperature cannot be negative.')
      If (It_NOCT < 0.d0) Call foundBadParameter(17,'Fatal','The global radiation on PV plane at NOCT conditions cannot be negative.')
      If ((Taualpha < 0.d0) .or. (Taualpha > 1.d0)) Call foundBadParameter(18,'Fatal','The effective transmittance-absorptance product must be between 0 and 1.')
      If (ErrorFound()) Return
      
   !Sample Code: If( PAR1 <= 0.) Call FoundBadParameter(1,'Fatal','The first parameter provided to this model is not acceptable.')

   !Set the Initial Values of the Outputs (#,Value)
		Call SetOutputValue(1, 0.d0) ! Pel - Electric power output
		Call SetOutputValue(2, 0.d0) ! Tcell - temperature of the PV cell
		Call SetOutputValue(3, 0.d0) ! EtaPV - total efficiency of PV modules


   !If Needed, Set the Initial Values of the Static Storage Variables (#,Value)
   !Sample Code: SetStaticArrayValue(1,0.d0)

   !If Needed, Set the Initial Values of the Dynamic Storage Variables (#,Value)
   !Sample Code: Call SetDynamicArrayValueThisIteration(1,20.d0)

   !If Needed, Set the Initial Values of the Discrete Controllers (#,Value)
   !Sample Code for Controller 1 Set to Off: Call SetDesiredDiscreteControlState(1,0) 

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!ReRead the Parameters if Another Unit of This Type Has Been Called Last
      If(getIsReReadParameters()) Then
		!Read in the Values of the Parameters from the Input File
      PVTmode = getParameterValue(1)
      PVmode = getParameterValue(2)
      PVcellmode = getParameterValue(3)
      Area = getParameterValue(4)
      Eta_ref = getParameterValue(5)
      b0 = getParameterValue(6)
      beta = getParameterValue(7)
      Tcell_ref = getParameterValue(8)
      a = getParameterValue(9)
      b = getParameterValue(10)
      c = getParameterValue(11)
      Ucellfl = getParameterValue(12)*3.6d0
      U0 = getParameterValue(13)*3.6d0
      U1 = getParameterValue(14)*3.6d0
      Tcell_NOCT = getParameterValue(15)
      Tamb_NOCT = getParameterValue(16)
      It_NOCT = getParameterValue(17)*3.6d0
      Taualpha = getParameterValue(18)

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!Read the Inputs
      It = GetInputValue(1)
      Theta = GetInputValue(2)
      Tm = GetInputValue(3)
      qth = GetInputValue(4)
      u = GetInputValue(5)
      Tamb = GetInputValue(6)
      Tcell_in = GetInputValue(7)
		

	!Check the Inputs for Problems (#,ErrorType,Text)
	!Sample Code: If( IN1 <= 0.) Call FoundBadInput(1,'Fatal','The first input provided to this model is not acceptable.')
      If(It < 0.d0) Call FoundBadInput(1,'Fatal','The global radiation on PV / PVT plane cannot be negative.')
      If(u < 0.d0) Call FoundBadInput(5,'Fatal','The wind speed in the PV plane cannot be negative.')
      If(ErrorFound()) Return
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!    *** PERFORM ALL THE CALCULATION HERE FOR THIS MODEL. ***
!-----------------------------------------------------------------------------------------------------------------------
                  
	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Previous Control States if Discrete Controllers are Being Used (#)
	!Sample Code: CONTROL_LAST=getPreviousControlState(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Values from the Global Storage Array for the Static Variables (#)
	!Sample Code: STATIC1=getStaticArrayValue(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Initial Values of the Dynamic Variables from the Global Storage Array (#)
	!Sample Code: T_INITIAL_1=getDynamicArrayValueLastTimestep(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
 	!Perform All of the Calculations Here to Set the Outputs from the Model Based on the Inputs

	!Sample Code: OUT1=IN1+PAR1   

	!If the model requires the solution of numerical derivatives, set these derivatives and get the current solution
	!Sample Code: T1=getNumericalSolution(1)
	!Sample Code: T2=getNumericalSolution(2)
	!Sample Code: DTDT1=3.*T2+7.*T1-15.
	!Sample Code: DTDT2=-2.*T1+11.*T2+21.
	!Sample Code: Call SetNumericalDerivative(1,DTDT1)
	!Sample Code: Call SetNumericalDerivative(2,DTDT2) 
      
!------------------------------------------------------------------------------
!    Calculation of PR IAM
!------------------------------------------------------------------------------
!Set the PRiam to zero if there is no incident solar, or if the incidence angle theta is 
!lower / greater than the possible acceptance angle (0° - 90°)

    If((It<=0.d0).or.(Theta<0.d0).or.(Theta>=90.d0)) Then
    
    PRiam = 0.d0
    
    Else
    
    PRiam = 1.d0-b0*(1.d0/cos(Theta*3.1415927d0/180.d0)-1.d0) 

    Endif

    ! Set PRiam to zero if PRiam is negative
    
    If(PRiam<0.d0) Then
   
    PRiam = 0.d0
   
    EndIf
    
!---------------------------------------------------------------------------------------


!------------------------------------------------------------------------------
!    Calculation of PR G
!------------------------------------------------------------------------------
    
    If(It>0.d0) Then
    
    PRg = a*It/3.6d0+b*LOG(It/3.6d0+1.d0)+c*((LOG(It/3.6d0+EXP(1.d0)))**2.d0/(It/3.6d0+1.d0)-1.d0) 
 
    Else
        
    PRg = 0.d0
    
    EndIf
    
!------------------------------------------------------------------------------
!    Calculation of Tcell
!------------------------------------------------------------------------------

    If(PVTmode==1) Then                         ! PVT model, internal calculation of cell temperature
    
    Tcell = qth/(Ucellfl)+Tm 
    
    Elseif(PVTmode==2) Then                     ! PV model
                      
        If(PVcellmode==1) Then                  ! Faiman model
    
        Tcell = Tamb + It/(U0+U1*u)
        
        Elseif(PVcellmode==2) Then              ! NOCT model, constant heat loss coefficient
            
!       Tcell = Tamb + It/It_NOCT * (Tcell_NOCT-Tamb_NOCT) * (1-Eta_ref/Taualpha)
  
        k1 = Eta_ref*PRiam*PRg
        k2 = It/It_NOCT * (Tcell_NOCT-Tamb_NOCT)
        Tcell = (Tamb + k2 * (1.d0-k1/Taualpha*(1.d0+beta/100.d0*Tcell_ref)))/(1.d0-k1*k2/Taualpha*beta/100.d0)
            
        Else                                    ! NOCT model, wind speed dependent heat loss coefficient
    
!      Tcell = Tamb + It/It_NOCT * 9.5d0/(5.7d0+3.8d0*u) * (Tcell_NOCT-Tamb_NOCT) * (1-Eta_ref/Taualpha)
            
        k1 = Eta_ref*PRiam*PRg
        k2 = It/It_NOCT * 9.5d0/(5.7d0+3.8d0*u) * (Tcell_NOCT-Tamb_NOCT)
        Tcell = (Tamb + k2 * (1.d0-k1/Taualpha*(1.d0+beta/100.d0*Tcell_ref)))/(1.d0-k1*k2/Taualpha*beta/100.d0)
        
        Endif
        
    Else
        
    Tcell = Tcell_in                            ! PVT model, external calculation of cell temperature
    
    Endif
!---------------------------------------------------------------------------------------


!------------------------------------------------------------------------------
!    Calculation of PR T
!------------------------------------------------------------------------------
      
    PRt = 1.d0 - beta/100.d0 * (Tcell-Tcell_ref) 
      
!---------------------------------------------------------------------------------------



      
!---------------------------------------------------------------------------------------

!------------------------------------------------------------------------------
!    Calculation of PRtot, Pelspec, Pel and EtaPV
!------------------------------------------------------------------------------
      
    PRtot = PRiam*PRt*PRg
    Pelspec = Eta_ref*PRtot*It
    Pel = Pelspec*Area
    EtaPV = Eta_ref*PRtot
    
!---------------------------------------------------------------------------------------



!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Outputs from this Model (#,Value)
		Call SetOutputValue(1, Pel) ! Pel - Electric power output
		Call SetOutputValue(2, Tcell) ! Tcell - temperature of the PV cell
		Call SetOutputValue(3, EtaPV) ! EtaPV - total efficiency of PV modules

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Desired Disceret Control Signal Values for this Iteration (#,State)
!Sample Code:  Call SetDesiredDiscreteControlState(1,1)
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Final value of the Dynamic Variables in the Global Storage Array (#,Value)
!Sample Code:  Call SetDynamicArrayValueThisIteration(1,T_FINAL_1)
!-----------------------------------------------------------------------------------------------------------------------
 
      Return
      End
!-----------------------------------------------------------------------------------------------------------------------

